//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffolding.CodeFirst.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartmentContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartmentContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scaffolding.CodeFirst.Resources.DepartmentContextResources", typeof(DepartmentContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

			        public static string Course { get { return ResourceManager.GetString("Course", resourceCulture); } }
		        public static string Course_Plural { get { return ResourceManager.GetString("Course_Plural", resourceCulture); } }
		        public static string Course_CourseID { get { return ResourceManager.GetString("Course_CourseID", resourceCulture); } }
		        public static string Course_Title { get { return ResourceManager.GetString("Course_Title", resourceCulture); } }
		        public static string Course_Department { get { return ResourceManager.GetString("Course_Department", resourceCulture); } }
		        public static string Department { get { return ResourceManager.GetString("Department", resourceCulture); } }
		        public static string Department_Plural { get { return ResourceManager.GetString("Department_Plural", resourceCulture); } }
		        public static string Department_DepartmentID { get { return ResourceManager.GetString("Department_DepartmentID", resourceCulture); } }
		        public static string Department_Name { get { return ResourceManager.GetString("Department_Name", resourceCulture); } }
		        public static string Employee { get { return ResourceManager.GetString("Employee", resourceCulture); } }
		        public static string Employee_Plural { get { return ResourceManager.GetString("Employee_Plural", resourceCulture); } }
		        public static string Employee_EmployeeID { get { return ResourceManager.GetString("Employee_EmployeeID", resourceCulture); } }
		        public static string Employee_Name { get { return ResourceManager.GetString("Employee_Name", resourceCulture); } }
		        public static string Employee_Department { get { return ResourceManager.GetString("Employee_Department", resourceCulture); } }
	
    }
}

